# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- build
- build_and_deploy

pool: myFlaskAgentPool

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'flask-ml-serviceconn'
  
  # Web app name
  webAppName: 'flask-ml-1203'

  # Environment name
  environmentName: 'flask-ml-service'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)/flask-sklearn/

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool: myFlaskAgentPool
    steps:    
    - script: |
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip install setup
        python3.9 -m pip install -r requirements.txt
      workingDirectory: $(projectRoot)

    - script: |
        export PATH=$HOME/.local/bin:$PATH
        make install
        make lint
      workingDirectory: $(projectRoot)
      displayName: 'Run lint tests'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop
      
- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: myFlaskAgentPool
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

            - task: AzureWebApp@1
              displayName: 'Deploy Azure Web App : flask-ml-1203'
              inputs:
                azureSubscription: $(azureServiceConnectionId)
                appName: $(webAppName)
                package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
                



